### PR TITLE
test

### LINKED ISSUE #3: Add A New Slide
## We Need More Slides
Grab another octocat and create a new slide from scratch.
If you need help, check out the Appendix in the training manual.

### PR DESCRIPTION
**Pull request by rageofgods**
### TEST PR
**this is test**
resolves #3

### CODE REVIEW

**Comment by eldoranstars** [comment]
nice gob!

**Comment by eldoranstars** [comment]
gj!

**Review by rkadim — APPROVED** [review]
Good!

**Review by eldoranstars — APPROVED** [review]
gj!

**Pull request merged**
